version: '3'

services:
  postgresql:
    image: postgres
    container_name: node_base
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=nodebase
      - POSTGRES_PASSWORD=nodebase
      - POSTGRES_DATABASE=nodebase
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-node_base
    ports:
      - '6379-6379'